services:
  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  

  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq:4.0.9-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  # mysql:
  #   image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
  #   container_name: mysql
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: trainee_management_db      
  #   volumes:
  #     - mysql-data:/data

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #     args:
  #       DOMAIN_OWNER: ${DOMAIN_OWNER}
  #       NUGET_REPO_NAME: ${NUGET_REPO_NAME}
  #       CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
  #       REGION: ${REGION}
  #   env_file:
  #     - ./docker/.env
  #   container_name: trainee-api
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   restart: on-failure
 
volumes:
  redis-data:
  # mysql-data:
  rabbitmq_data:
